/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Chip: typeof import('primevue/chip')['default']
    Column: typeof import('primevue/column')['default']
    ColumnGroup: typeof import('primevue/columngroup')['default']
    CustomTable: typeof import('./src/components/CustomTable.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    GroupButtons: typeof import('./src/components/GroupButtons.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    Row: typeof import('primevue/row')['default']
    SearchPlayer: typeof import('./src/components/SearchPlayer.vue')['default']
    Select: typeof import('primevue/select')['default']
    SelectTeam: typeof import('./src/components/SelectTeam.vue')['default']
    SiteTitle: typeof import('./src/components/SiteTitle.vue')['default']
    Slider: typeof import('primevue/slider')['default']
    Statistic: typeof import('./src/components/Statistic.vue')['default']
    Statistics: typeof import('./src/components/Statistics.vue')['default']
    TableTeam: typeof import('./src/components/TableTeam.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
